"""initial schema

Revision ID: 2795c8119dad
Revises:
Create Date: 2026-03-02 17:07:31.756462

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "2795c8119dad"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_account_email"), "account", ["email"], unique=True)
    op.create_table(
        "delivery_partner",
        sa.Column("delivery_partner_id", sa.Uuid(), nullable=False),
        sa.Column("deliverable_zip_codes", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("max_handling_capacity", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "Pending", "Approved", "Banned", name="delivery_partner_status_enum"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["delivery_partner_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("delivery_partner_id"),
    )
    op.create_table(
        "refresh_token",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_token_account_id"),
        "refresh_token",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_token_token_hash"),
        "refresh_token",
        ["token_hash"],
        unique=False,
    )
    op.create_table(
        "seller",
        sa.Column("seller_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("Pending", "Approved", "Banned", name="seller_status_enum"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("seller_id"),
    )
    op.create_table(
        "shipment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "content", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("destination", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("Pending", "InTransit", "Delivered", name="shipment_status_enum"),
            nullable=False,
        ),
        sa.Column("estimated_delivery", sa.DateTime(timezone=True), nullable=True),
        sa.Column("seller_id", sa.Uuid(), nullable=False),
        sa.Column("delivery_partner_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["delivery_partner_id"],
            ["delivery_partner.delivery_partner_id"],
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["seller.seller_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shipment")
    op.drop_table("seller")
    op.drop_index(op.f("ix_refresh_token_token_hash"), table_name="refresh_token")
    op.drop_index(op.f("ix_refresh_token_account_id"), table_name="refresh_token")
    op.drop_table("refresh_token")
    op.drop_table("delivery_partner")
    op.drop_index(op.f("ix_account_email"), table_name="account")
    op.drop_table("account")
    # ### end Alembic commands ###
