"""add nnew indexes and info

Revision ID: 7e22e8dc3238
Revises: f4f3a9b5e2ce
Create Date: 2026-03-13 19:14:38.571755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7e22e8dc3238'
down_revision: Union[str, Sequence[str], None] = 'f4f3a9b5e2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('seller', sa.Column('seller_zip_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('shipment', sa.Column('destination_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('shipment', sa.Column('destination_zip', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('shipment', 'delivery_partner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_shipment_delivery_partner_id'), 'shipment', ['delivery_partner_id'], unique=False)
    op.create_index(op.f('ix_shipment_seller_id'), 'shipment', ['seller_id'], unique=False)
    op.drop_column('shipment', 'destination')
    op.add_column('shipment_event', sa.Column('current_location', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('shipment_event', sa.Column('current_location_zip', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_shipment_event_shipment_id'), 'shipment_event', ['shipment_id'], unique=False)
    op.drop_column('shipment_event', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment_event', sa.Column('location', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_shipment_event_shipment_id'), table_name='shipment_event')
    op.drop_column('shipment_event', 'current_location_zip')
    op.drop_column('shipment_event', 'current_location')
    op.add_column('shipment', sa.Column('destination', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_shipment_seller_id'), table_name='shipment')
    op.drop_index(op.f('ix_shipment_delivery_partner_id'), table_name='shipment')
    op.alter_column('shipment', 'delivery_partner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('shipment', 'destination_zip')
    op.drop_column('shipment', 'destination_address')
    op.drop_column('seller', 'seller_zip_code')
    op.drop_column('account', 'is_active')
    # ### end Alembic commands ###
