"""Add shipement_events table

Revision ID: f4f3a9b5e2ce
Revises: 2795c8119dad
Create Date: 2026-03-13 14:23:23.938915

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f4f3a9b5e2ce"
down_revision: Union[str, Sequence[str], None] = "2795c8119dad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shipment_event",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("shipment_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("location", sa.Integer(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipment.id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.add_column(
        "seller",
        sa.Column("seller_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.execute(
        "UPDATE seller SET seller_address='not available' WHERE seller_address IS NULL"
    )
    op.alter_column("seller", "seller_address", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("seller", "seller_address")
    op.drop_table("shipment_event")
    # ### end Alembic commands ###
